version: '3.8'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '8080:3000'
    environment:
      NODE_ENV: production
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE_NAME: nestapi
      PORT: 3000
      DB_SYNC: 'true'
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestapi
    ports:
      - '35000:5432'
